execute pathogen#infect()
set shiftwidth=2
set tabstop=2
set smartindent
set mouse=a
set cindent
filetype plugin indent on
set omnifunc=syntaxcomplete#Complete
colorscheme pablo
set laststatus=2
set statusline+=%F
syntax on
set number
set wrap
set linebreak
set nolist  " list disables linebreak
set textwidth=0
set wrapmargin=0
set formatoptions+=l
hi StatusLine ctermbg=none
